# This workflow builds and tests a cross platform python package

name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Job ${{matrix.id}}. Python ${{ matrix.python }} on ${{matrix.os}}.
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
          # Legacy Tests: Python 3.8 - 3.10 on Ubuntu
          - {id: 1, python: "3.8", os: ubuntu-latest }
          - {id: 2, python: "3.9", os: ubuntu-latest }
          - {id: 4, python: "3.10", os: ubuntu-latest }
          # Cross Platform Tests. Python 3.11 on Windows, Mac, and Ubuntu
          - {id: 5, python: "3.11", os: ubuntu-latest }
          - {id: 6, python: "3.11", os: windows-latest }
          - {id: 7, python: "3.11", os: macos-latest }
          # 3.12 support currently impossible due to numba
          
    steps:
    - name: Fetch Repo
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}

    - name: Update pip
      run: pip install -U pip

    - name: Install package
      run: pip install .
    
    - name: Test package
      run: pytest

    - name: Lint package
      run: flake8
